Repository ProvableHQ/snarkVM, pull requests merged in 2024-06, with the labels that each got.

#2483 [HackerOne-2498849] Only abort deploys early in prepare_for_speculate
  ledger/Cargo.toml
  ledger/src/tests.rs
  synthesizer/src/vm/finalize.rs
Labels: requires-ledger-reset

#2486 Increase mainnet MAX_CERTIFICATES, and thereby max number of validators
  console/network/src/mainnet_v0.rs
Labels: requires-ledger-reset, genesis resampling mainnet

#2456 Fairly price storage costs for transactions
  console/network/src/lib.rs
  synthesizer/process/src/cost.rs
  synthesizer/process/src/lib.rs
  synthesizer/tests/expectations/vm/execute_and_finalize/complex_finalization.out
  synthesizer/tests/expectations/vm/execute_and_finalize/many_input_and_output.out
Labels: requires-ledger-reset

#2492 updating to Canary genesis block v0.2.1
  README.md
  parameters/src/canary/resources/block.genesis
Labels: enhancement, requires-ledger-reset

#2501 Fix header image, links, build instructions, rightsize CI
  .circleci/config.yml
  README.md
Labels: enhancement
