Repository ProvableHQ/snarkVM, pull requests merged in 2024-11, with the labels that each got.

#2559 Fix serde
  ledger/block/src/header/metadata/serialize.rs
  ledger/block/src/lib.rs
Labels: bug, v1.1.4

#2563 [Perf] Use heuristics to avoid allocations in Sanitizer::str_till_eol
  console/network/environment/src/helpers/sanitizer.rs
Labels: enhancement, v1.1.4

#2569 [ARC-0042] Adjust reward algorithms to utilize timestamps
  console/network/src/canary_v0.rs
  console/network/src/lib.rs
  console/network/src/mainnet_v0.rs
  console/network/src/testnet_v0.rs
  ledger/block/src/helpers/target.rs
  ledger/block/src/verify.rs
  ledger/src/advance.rs
  ledger/src/check_next_block.rs
  synthesizer/src/vm/finalize.rs
  synthesizer/src/vm/mod.rs
  synthesizer/src/vm/verify.rs
  synthesizer/tests/test_vm_execute_and_finalize.rs
Labels: enhancement, v1.1.4

#2573 [Cleanup] Minor compilation and clippy fix
  ledger/block/src/lib.rs
  synthesizer/process/src/cost.rs
Labels: bug, v1.1.4

#2500 [Chore] Use type_name instead of literals for LiteralType::parse
  console/program/src/data_types/literal_type/mod.rs
  console/program/src/data_types/literal_type/parse.rs
Labels: v1.2.1
