Repository ProvableHQ/snarkVM, pull requests merged in 2025-07, with the labels that each got.

#2790 Introduce ConsensusVersion V8 and increase constraint limit
  console/network/src/canary_v0.rs
  console/network/src/lib.rs
  console/network/src/mainnet_v0.rs
  console/network/src/testnet_v0.rs
Labels: 4.0.0

#2792 [Feat] Implement new Inclusion version
  circuit/collections/src/merkle_tree/leaf_index.rs
  circuit/collections/src/merkle_tree/mod.rs
  circuit/program/src/state_path/mod.rs
  console/network/src/canary_v0.rs
  console/network/src/lib.rs
  console/network/src/mainnet_v0.rs
  console/network/src/testnet_v0.rs
  ledger/block/src/transaction/fee/mod.rs
  ledger/block/src/transaction/mod.rs
  ledger/block/src/transition/mod.rs
  parameters/examples/inclusion.rs
  parameters/src/canary/mod.rs
  parameters/src/canary/resources/inclusion.metadata
  parameters/src/canary/resources/inclusion.verifier
  parameters/src/canary/resources/inclusion_v0.metadata
  parameters/src/canary/resources/inclusion_v0.verifier
  parameters/src/canary/resources/upgrade.metadata
  parameters/src/canary/resources/upgrade.verifier
  parameters/src/mainnet/mod.rs
  parameters/src/mainnet/resources/inclusion.metadata
  parameters/src/mainnet/resources/inclusion.verifier
  parameters/src/mainnet/resources/inclusion_v0.metadata
  parameters/src/mainnet/resources/inclusion_v0.verifier
  parameters/src/mainnet/resources/upgrade.metadata
  parameters/src/mainnet/resources/upgrade.verifier
  parameters/src/testnet/mod.rs
  parameters/src/testnet/resources/inclusion.metadata
  parameters/src/testnet/resources/inclusion.verifier
  parameters/src/testnet/resources/inclusion_v0.metadata
  parameters/src/testnet/resources/inclusion_v0.verifier
  parameters/src/testnet/resources/upgrade.metadata
  parameters/src/testnet/resources/upgrade.verifier
  synthesizer/process/src/stack/authorization/mod.rs
  synthesizer/process/src/tests/test_execute.rs
  synthesizer/process/src/trace/inclusion/assignment.rs
  synthesizer/process/src/trace/inclusion/assignment_v0.rs
  synthesizer/process/src/trace/inclusion/mod.rs
  synthesizer/process/src/trace/inclusion/prepare.rs
  synthesizer/process/src/trace/mod.rs
  synthesizer/process/src/verify_execution.rs
  synthesizer/process/src/verify_fee.rs
  synthesizer/program/src/resources/credits.aleo
  synthesizer/src/vm/execute.rs
  synthesizer/src/vm/finalize.rs
  synthesizer/src/vm/mod.rs
  synthesizer/src/vm/verify.rs
Labels: 4.0.0

#2796 Clean up Record V0 error
  circuit/program/src/request/verify.rs
  console/program/src/request/sign.rs
  synthesizer/process/src/execute.rs
  synthesizer/process/src/tests/test_credits.rs
Labels: 4.0.0

#2802 Port authorize_unchecked to canary
  synthesizer/process/src/authorize.rs
  synthesizer/process/src/evaluate.rs
  synthesizer/process/src/stack/authorize.rs
  synthesizer/process/src/stack/call/mod.rs
  synthesizer/process/src/stack/evaluate.rs
  synthesizer/process/src/stack/execute.rs
  synthesizer/process/src/stack/registers/call.rs
  synthesizer/process/src/tests/test_execute.rs
  synthesizer/process/src/traits/mod.rs
  synthesizer/program/src/logic/instruction/operation/literals.rs
  synthesizer/src/vm/mod.rs
  synthesizer/tests/test_process_execute.rs
  synthesizer/tests/utilities/tests/program_test.rs
Labels: 4.0.0

#2800 Fail loudly when using the wrong program or record version
  .rusty-hook.toml
  synthesizer/process/src/stack/authorization/mod.rs
  synthesizer/process/src/verify_execution.rs
  synthesizer/process/src/verify_fee.rs
  synthesizer/src/vm/execute.rs
Labels: 4.0.0

#2826 Increase to 40 validators
  console/network/src/canary_v0.rs
  console/network/src/consensus_heights.rs
  console/network/src/lib.rs
  console/network/src/mainnet_v0.rs
  console/network/src/testnet_v0.rs
Labels: v4.1.0

#2825 Do not determine consensus version based on user-submitted height
  synthesizer/src/vm/mod.rs
  synthesizer/src/vm/verify.rs
Labels: requires-sync-test
